name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build Print3DCloud.Client/Print3DCloud.Client.csproj --no-restore --runtime win-x64
        dotnet build Print3DCloud.Client/Print3DCloud.Client.csproj --no-restore --runtime linux-x64
        dotnet build Print3DCloud.Client/Print3DCloud.Client.csproj --no-restore --runtime linux-arm
        dotnet build Print3DCloud.Client/Print3DCloud.Client.csproj --no-restore --runtime linux-arm64

    - name: Test
      run: dotnet test --verbosity normal
