name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-win-x64:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Build
      run: dotnet build Print3DCloud.Client/Print3DCloud.Client.csproj --runtime win-x64 --no-self-contained

  build-linux-x64:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Build
      run: dotnet build Print3DCloud.Client/Print3DCloud.Client.csproj --runtime linux-x64 --no-self-contained
      
  build-linux-arm:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Build
      run: dotnet build Print3DCloud.Client/Print3DCloud.Client.csproj --runtime linux-arm --no-self-contained

  test:
    runs-on: ubuntu-latest
    needs:
    - build-win-x64
    - build-linux-x64
    - build-linux-arm

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Run ActionCableSharp tests
      working-directory: ActionCableSharp.Tests
      run: dotnet test --collect:"XPlat Code Coverage" --logger "console;verbosity=normal"

    - name: Run Print3DCloud.Client tests
      working-directory: Print3DCloud.Client.Tests
      run: dotnet test --collect:"XPlat Code Coverage" --logger "console;verbosity=normal"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: '**/TestResults/**/coverage.cobertura.xml'
